### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by aeimskei** [aeimskei/cyber-security-club#11]
* Do we need more stuff for the footer?
* Are there social media channels?

**Comment by NanaRei** [comment]
I don't have any links right now but I was thinking of creating a LinkedIn page for the club, which you can place the LinkedIn logo here. Not sure if we will do FB or Instagram but that might be too much since we already have Slack. How about a link to youtube where we place all our videos for club events? Can someone look into how to create the Youtube channel/page and what we will need to have an account and to upload the videos to it? Thank you.

**Comment by aeimskei** [comment]
I'm gonna turn this into a Resource dropdown tab in the Navbar instead. Don't want to clutter the Footer.

**Comment by aeimskei** [comment]
Is there a link for Student Handbook?
